### ISSUE TITLE
Should install_url() follow redirects?

### ISSUE THREAD

**Issue by krlmlr** [MangoTheCat/remotes#42]
e.g., `install_url('https://github.com/krlmlr/devtools/raw/develop/bin/devtools_1.12.0.9001.zip')`

**Comment by gaborcsardi** [comment]
It does not? I think it should.

**Comment by krlmlr** [comment]
At least not on R 3.0.0 on Windows:

https://ci.appveyor.com/project/krlmlr/r-appveyor/build/1.0.1138

**Comment by krlmlr** [comment]
Apologies. It doesn't work even if I add the redirect.

**Comment by gaborcsardi** [comment]
But wait, so it **does** redirect now?
